env:
    amd: true
    browser: true
    commonjs: true
    es6: true
    jquery: true
extends: 'eslint:recommended'
globals:
    Atomics: readonly
    SharedArrayBuffer: readonly
parserOptions:
    ecmaVersion: 2018
    sourceType: module
rules:
    indent:
        - error
        - 4
        - {
            SwitchCase: 1
        }
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
